#!/bin/bash

images=$(docker images -a | grep "<none>" | sed "s#[[:space:]][[:space:]]*# #g" | cut -d' ' -f3)
if [ "_$images" == "_" ]
then
	echo "No untagged image found"
else
	echo "Removing untagged images: $images"
	docker rmi -f $images
fi
