#!/bin/bash

set -e

function usage() {
	echo "Usage: $0 <debian file>" >&2
	echo >&2
	echo "This script is intended to be used in addition to checkinstall to produce retail and dev package." >&2
	echo "" >&2
	echo "Package must be named <package>-all_<version>_<arch>.deb" >&2
	echo "Script will produce 2 files:" >&2
	echo "  <package>_<version>_<arch>.deb for retail version" >&2
	echo "  <package>-dev_<version>_<arch>.deb for dev version" >&2
}

if [ $# -ne 1 ]
then
	usage
	exit 1
fi

deb_file=$1
deb_dev_file=$(basename ${deb_file} | sed -e "s#\(.*\)-all_\(.*\)#\1-dev_\2#g")
deb_retail_file=$(basename ${deb_file} | sed -e "s#\(.*\)-all_\(.*\)#\1_\2#g")

pkg_name=$(basename ${deb_file} | sed -e "s#\(.*\)-all_.*#\1#g")
pkg_all_name=$(basename ${deb_file} | sed -e "s#\(.*-all\)_.*#\1#g")
pkg_dev_name=$(basename ${deb_file} | sed -e "s#\(.*\)-all_.*#\1-dev#g")
pkg_retail_name=$(basename ${deb_file} | sed -e "s#\(.*\)-all_.*#\1#g")

install=0
[[ "_$(dpkg -l | grep ${pkg_name})" == "_" ]] || install=1

# remove packages
[ $install -eq 1 ] && dpkg -r ${pkg_all_name}
[ $install -eq 1 ] && dpkg -r ${pkg_dev_name}
[ $install -eq 1 ] && dpkg -r ${pkg_retail_name}

output=$(mktemp -d)

rm -rf ${output}/split-deb-dev
mkdir ${output}/split-deb-dev

# unpack debian package
dpkg-deb -x ${deb_file} ${output}/split-deb-dev
dpkg-deb --control ${deb_file} ${output}/split-deb-dev/DEBIAN

function create_retail() {
	retail_name=$(basename ${deb_file} | sed -e 's#-all##g')
	
	# copy package structure
	rm -rf ${output}/split-deb-retail
	mkdir ${output}/split-deb-retail
	cp -rf ${output}/split-deb-dev/DEBIAN ${output}/split-deb-retail
	
	# modify control file
	sed -i -e "s#\(Package: .*\)-all#\1#g" ${output}/split-deb-retail/DEBIAN/control
	sed -i -e '/Installed-Size:.*/d' ${output}/split-deb-retail/DEBIAN/control
	sed -i -e "s#\(Provides: .*\)-all#\1#g" ${output}/split-deb-retail/DEBIAN/control
	
	# change dev dependancies to retail
	while [ "_$(grep 'Depends:' ${output}/split-deb-retail/DEBIAN/control | grep -- '-dev')" != "_" ]
	do
		sed -i -e "s#\(Depends: .*\)-dev\(.*\)#\1\2#g" ${output}/split-deb-retail/DEBIAN/control
	done
	
	# copy so files
	for file in $(find ${output}/split-deb-dev -name "*.so*" -o -name "*.a")
	do
		relfile=$(echo $file | sed "s#${output}/split-deb-dev/##g")
		path=$(dirname $relfile)
		name=$(basename $relfile)
		
		mkdir -p ${output}/split-deb-retail/${path}
		cp -a ${file} ${output}/split-deb-retail/${path}/
	done
	
	# create package
	dpkg -b ${output}/split-deb-retail ${retail_name}
}

function create_dev() {
	dev_name=$(basename ${deb_file} | sed -e 's#-all#-dev#g')
	
	# remove so from dev package
	find ${output}/split-deb-dev -name "*.so*" -type f -exec rm -f {} \;
	find ${output}/split-deb-dev -name "*.so*" -type l -exec rm -f {} \;
	find ${output}/split-deb-dev -name "*.a" -type f -exec rm -f {} \;
		
	# modify control file
	retail_name=$(grep "Package:" ${output}/split-deb-dev/DEBIAN/control | sed -e "s#Package: \(.*\)-all#\1#g")
	sed -i -e '/Installed-Size:.*/d' ${output}/split-deb-dev/DEBIAN/control
	sed -i -e 's/-all/-dev/g' ${output}/split-deb-dev/DEBIAN/control

	# add dependency to retail package
	if [ "_$(grep 'Depends:' ${output}/split-deb-dev/DEBIAN/control)" == "_" ]
	then
		echo "Depends: ${retail_name}" >> ${output}/split-deb-dev/DEBIAN/control
	else
		sed -i -e "s#\(Depends:.*\)#\1,${retail_name}#g" ${output}/split-deb-dev/DEBIAN/control	
	fi
	
	# remove empty directories
	while [ -n "$(find ${output}/split-deb-dev -depth -type d -empty -exec rmdir {} +)" ]; do :; done
	
	# create package
	dpkg -b ${output}/split-deb-dev ${dev_name}
}

# create retail package
create_retail

# create dev package
create_dev

#install packages
[ $install -eq 1 ] && dpkg -i ${deb_retail_file}
[ $install -eq 1 ] && dpkg -i ${deb_dev_file}

# cleanup
rm -rf ${output}

