#!/bin/bash

set -e

xpl_path=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

function usage() {
	echo "Usage: $0 <mirror> <ppa> <repository> <expression> [<options>]" >&2
	echo >&2
	echo "Options:"
	#	echo "  --distribution=name          = change distribution (default=${distribution})" >&2
	echo >&2
}

if [ $# -lt 4 ]
then
	usage
	exit 1
fi


mirror=""
ppa=""
repository=""
expression=""
while [[ "_$*" != "_" ]]
do
    if [ "_$(echo "$1" | grep '=')" != "_" ]
    then
        filt_arg="$(echo $1 | sed "s#\(.*\)=.*#\1#g")"
        value_arg="$(echo $1 | sed "s#.*=\(.*\)#\1#g")"
    else
        filt_arg=$1
        unset value_arg
    fi

	if [[ "$filt_arg" == "--distribution" ]]; then
	    distribution=$value_arg
	elif [[ "_$mirror" == "_" ]]; then
	    mirror=$filt_arg
	elif [[ "_$ppa" == "_" ]]; then
	    ppa=$filt_arg
	elif [[ "_$repository" == "_" ]]; then
	    repository=$filt_arg
	elif [[ "_$expression" == "_" ]]; then
	    expression=$filt_arg
	fi
	
	shift
done

# check ssh
${xpl_path}/check-ssh ${ppa} ${mirror}

#ssh ${ppa}@${mirror} aptly package search "'Name (${expression})'"
packages=$(ssh ${ppa}@${mirror} aptly package search "'Name (${expression})'" 2>/dev/null)
#[ $? -ne 0 ] && exit 1

# search expression
if [[ "_${packages}" == "_" ]]
then
	echo 0
else
	echo 1
fi

exit 0
